# Generated by Django 5.1.7 on 2026-06-05 02:36

import django.db.models.deletion
import django.utils.timezone
import shifttimes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_group_agree_remove_group_allow_jpnic_add_and_more'),
        ('shift', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalShiftTemplate',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'historical シフトテンプレート',
                'verbose_name_plural': 'historical シフトテンプレート',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to='custom_auth.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_templates', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'シフトテンプレート',
                'verbose_name_plural': 'シフトテンプレート',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalShiftTemplateItem',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('status', models.CharField(blank=True, choices=[('', '未回答'), ('available', '勤務可能'), ('unavailable', '勤務不可'), ('maybe', '要相談')], default='', max_length=20, verbose_name='ステータス')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('time_slot', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shift.timeslot', verbose_name='時間帯')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shift.shifttemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'historical シフトテンプレート明細',
                'verbose_name_plural': 'historical シフトテンプレート明細',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftTemplateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('status', models.CharField(blank=True, choices=[('', '未回答'), ('available', '勤務可能'), ('unavailable', '勤務不可'), ('maybe', '要相談')], default='', max_length=20, verbose_name='ステータス')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shift.shifttemplate', verbose_name='テンプレート')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shift_template_items', to='shift.timeslot', verbose_name='時間帯')),
            ],
            options={
                'verbose_name': 'シフトテンプレート明細',
                'verbose_name_plural': 'シフトテンプレート明細',
                'ordering': ('time_slot__start_time',),
            },
        ),
        migrations.AddIndex(
            model_name='shifttemplate',
            index=models.Index(fields=['group', 'user'], name='shift_shift_group_i_b0d0df_idx'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplate',
            constraint=models.UniqueConstraint(fields=('group', 'user', 'name'), name='shift_template_unique_name'),
        ),
        migrations.AddConstraint(
            model_name='shifttemplateitem',
            constraint=models.UniqueConstraint(fields=('template', 'time_slot'), name='shift_template_item_unique_time_slot'),
        ),
    ]
