# Generated by Django 5.1.7 on 2026-06-05 02:55

import django.db.models.deletion
import django.utils.timezone
import shifttimes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_group_agree_remove_group_allow_jpnic_add_and_more'),
        ('shift', '0002_historicalshifttemplate_shifttemplate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalOpeningScheduleType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='区分名')),
                ('blocks_shift_input', models.BooleanField(default=False, verbose_name='シフト入力不可')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='表示順')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 開講区分',
                'verbose_name_plural': 'historical 開講区分',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='OpeningScheduleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='区分名')),
                ('blocks_shift_input', models.BooleanField(default=False, verbose_name='シフト入力不可')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='表示順')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_schedule_types', to='custom_auth.group', verbose_name='グループ')),
            ],
            options={
                'verbose_name': '開講区分',
                'verbose_name_plural': '開講区分',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalWeeklyOpeningSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], verbose_name='曜日')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shift.openingscheduletype', verbose_name='開講区分')),
            ],
            options={
                'verbose_name': 'historical 曜日別開講スケジュール',
                'verbose_name_plural': 'historical 曜日別開講スケジュール',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDateOpeningSchedule',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('work_date', models.DateField(db_index=True, verbose_name='日付')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule_type', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shift.openingscheduletype', verbose_name='開講区分')),
            ],
            options={
                'verbose_name': 'historical 日付別開講スケジュール',
                'verbose_name_plural': 'historical 日付別開講スケジュール',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DateOpeningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('work_date', models.DateField(db_index=True, verbose_name='日付')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_opening_schedules', to='custom_auth.group', verbose_name='グループ')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='date_opening_schedules', to='shift.openingscheduletype', verbose_name='開講区分')),
            ],
            options={
                'verbose_name': '日付別開講スケジュール',
                'verbose_name_plural': '日付別開講スケジュール',
                'ordering': ('work_date',),
            },
        ),
        migrations.CreateModel(
            name='WeeklyOpeningSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, '月'), (1, '火'), (2, '水'), (3, '木'), (4, '金'), (5, '土'), (6, '日')], verbose_name='曜日')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_opening_schedules', to='custom_auth.group', verbose_name='グループ')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weekly_opening_schedules', to='shift.openingscheduletype', verbose_name='開講区分')),
            ],
            options={
                'verbose_name': '曜日別開講スケジュール',
                'verbose_name_plural': '曜日別開講スケジュール',
                'ordering': ('weekday',),
            },
        ),
        migrations.AddConstraint(
            model_name='openingscheduletype',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='opening_schedule_type_unique_name'),
        ),
        migrations.AddIndex(
            model_name='dateopeningschedule',
            index=models.Index(fields=['group', 'work_date'], name='shift_dateo_group_i_f6399d_idx'),
        ),
        migrations.AddConstraint(
            model_name='dateopeningschedule',
            constraint=models.UniqueConstraint(fields=('group', 'work_date'), name='date_opening_schedule_unique_date'),
        ),
        migrations.AddConstraint(
            model_name='weeklyopeningschedule',
            constraint=models.UniqueConstraint(fields=('group', 'weekday'), name='weekly_opening_schedule_unique_weekday'),
        ),
    ]
