# Generated by Django 5.1.7 on 2026-06-09 21:53

import django.db.models.deletion
import django.utils.timezone
import shifttimes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_group_stripe_subscription_id_and_more'),
        ('shift', '0003_historicalopeningscheduletype_openingscheduletype_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshiftentry',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='下書き'),
        ),
        migrations.AddField(
            model_name='shiftentry',
            name='is_draft',
            field=models.BooleanField(db_index=True, default=False, verbose_name='下書き'),
        ),
        migrations.CreateModel(
            name='HistoricalShiftDeadline',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('period_start', models.DateField(verbose_name='対象期間 開始日')),
                ('period_end', models.DateField(verbose_name='対象期間 終了日')),
                ('deadline_date', models.DateField(verbose_name='提出期限日')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical シフト提出期限',
                'verbose_name_plural': 'historical シフト提出期限',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ShiftDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('period_start', models.DateField(verbose_name='対象期間 開始日')),
                ('period_end', models.DateField(verbose_name='対象期間 終了日')),
                ('deadline_date', models.DateField(verbose_name='提出期限日')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_deadlines', to='custom_auth.group', verbose_name='グループ')),
            ],
            options={
                'verbose_name': 'シフト提出期限',
                'verbose_name_plural': 'シフト提出期限',
                'ordering': ('period_start',),
                'constraints': [models.UniqueConstraint(fields=('group', 'period_start'), name='shift_deadline_unique_period')],
            },
        ),
    ]
