# Generated by Django 5.1.7 on 2026-09-18 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0005_remove_weeklyopeningschedule_group_and_more'),
    ]

    operations = [
        # SQLite はテーブル再構築を伴うため、フィールドより先に一意制約を落とす
        migrations.RemoveConstraint(
            model_name='shifttemplate',
            name='shift_template_unique_name',
        ),
        migrations.RemoveConstraint(
            model_name='shifttemplateitem',
            name='shift_template_item_unique_time_slot',
        ),
        migrations.RemoveField(
            model_name='historicalshifttemplateitem',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalshifttemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='historicalshifttemplateitem',
            name='time_slot',
        ),
        migrations.RemoveField(
            model_name='shifttemplate',
            name='group',
        ),
        migrations.RemoveField(
            model_name='shifttemplate',
            name='user',
        ),
        migrations.RemoveField(
            model_name='shifttemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='shifttemplateitem',
            name='time_slot',
        ),
        migrations.DeleteModel(
            name='HistoricalShiftTemplate',
        ),
        migrations.DeleteModel(
            name='HistoricalShiftTemplateItem',
        ),
        migrations.DeleteModel(
            name='ShiftTemplate',
        ),
        migrations.DeleteModel(
            name='ShiftTemplateItem',
        ),
    ]
