# Generated by Django 5.1.7 on 2026-09-18 02:27

import django.db.models.deletion
import django.utils.timezone
import shifttimes.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_group_stripe_subscription_id_and_more'),
        ('shift', '0006_remove_historicalshifttemplateitem_history_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='勤怠管理を利用する')),
                ('allow_manual_input', models.BooleanField(default=True, verbose_name='手動入力を許可')),
                ('allow_clock_button', models.BooleanField(default=True, verbose_name='出退勤ボタンを許可')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_setting', to='custom_auth.group', verbose_name='グループ')),
            ],
            options={
                'verbose_name': '勤怠設定',
                'verbose_name_plural': '勤怠設定',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceRecord',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('work_date', models.DateField(db_index=True, verbose_name='勤務日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='休憩時間（分）')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('source', models.CharField(choices=[('manual', '手動入力'), ('clock', '打刻')], default='manual', max_length=20, verbose_name='入力方法')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'historical 勤怠実績',
                'verbose_name_plural': 'historical 勤怠実績',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAttendanceSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='勤怠管理を利用する')),
                ('allow_manual_input', models.BooleanField(default=True, verbose_name='手動入力を許可')),
                ('allow_clock_button', models.BooleanField(default=True, verbose_name='出退勤ボタンを許可')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical 勤怠設定',
                'verbose_name_plural': 'historical 勤怠設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('work_date', models.DateField(db_index=True, verbose_name='勤務日')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='出勤時刻')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='退勤時刻')),
                ('break_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='休憩時間（分）')),
                ('note', shifttimes.models.MediumTextField(blank=True, default='', verbose_name='メモ')),
                ('source', models.CharField(choices=[('manual', '手動入力'), ('clock', '打刻')], default='manual', max_length=20, verbose_name='入力方法')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='custom_auth.group', verbose_name='グループ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '勤怠実績',
                'verbose_name_plural': '勤怠実績',
                'ordering': ('work_date',),
                'indexes': [models.Index(fields=['group', 'work_date'], name='shift_atten_group_i_72659a_idx'), models.Index(fields=['user', 'work_date'], name='shift_atten_user_id_c566f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('group', 'user', 'work_date'), name='attendance_record_unique_day')],
            },
        ),
    ]
