# Generated by Django 5.2.17 on 2026-09-21 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_group_free_plan_group_free_reason_and_more'),
        ('shift', '0007_attendancesetting_historicalattendancerecord_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaltimeslot',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical 勤務時間', 'verbose_name_plural': 'historical 勤務時間'},
        ),
        migrations.AlterModelOptions(
            name='timeslot',
            options={'ordering': ('start_time',), 'verbose_name': '勤務時間', 'verbose_name_plural': '勤務時間'},
        ),
        migrations.AddField(
            model_name='historicaltimeslot',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ'),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='custom_auth.group', verbose_name='グループ'),
        ),
    ]
