# Generated by Django 5.2.17 on 2026-09-21 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_group_free_plan_group_free_reason_and_more'),
        ('shift', '0009_time_slot_group_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslot',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='custom_auth.group', verbose_name='グループ'),
        ),
        migrations.AddIndex(
            model_name='timeslot',
            index=models.Index(fields=['group', 'start_time'], name='shift_times_group_i_983d20_idx'),
        ),
        migrations.AddConstraint(
            model_name='timeslot',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='time_slot_unique_name'),
        ),
    ]
