# Generated by Django 5.2.17 on 2026-09-21 03:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift', '0010_time_slot_group_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopeningscheduletype',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=7, validators=[django.core.validators.RegexValidator(message='表示色は #rrggbb の形式で指定してください。', regex='^#[0-9a-fA-F]{6}$')], verbose_name='表示色'),
        ),
        migrations.AddField(
            model_name='openingscheduletype',
            name='color',
            field=models.CharField(default='#0d6efd', max_length=7, validators=[django.core.validators.RegexValidator(message='表示色は #rrggbb の形式で指定してください。', regex='^#[0-9a-fA-F]{6}$')], verbose_name='表示色'),
        ),
    ]
