# Generated by Django 5.2.17 on 2026-09-21 04:00

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_group_free_plan_group_free_reason_and_more'),
        ('shift', '0012_opening_schedule_type_color_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshiftdeadline',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='リマインド送信日時'),
        ),
        migrations.AddField(
            model_name='shiftdeadline',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='リマインド送信日時'),
        ),
        migrations.CreateModel(
            name='HistoricalSlackNotificationSetting',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Slack通知を利用する')),
                ('mention', models.CharField(blank=True, default='', help_text='例: <!here>、<!channel>、<@U01ABCDEFG>', max_length=100, verbose_name='メンション')),
                ('notify_deadline_reminder', models.BooleanField(default=True, verbose_name='提出期限のリマインド')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='リマインドする日数（期限の何日前）')),
                ('notify_shift_confirmed', models.BooleanField(default=False, verbose_name='メンバーのシフト確定')),
                ('notify_schedule_changed', models.BooleanField(default=True, verbose_name='提出期限・開講スケジュールの変更')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('group', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Slack通知設定',
                'verbose_name_plural': 'historical Slack通知設定',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='SlackNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='Slack通知を利用する')),
                ('webhook_url', models.URLField(blank=True, default='', max_length=500, verbose_name='Incoming Webhook URL')),
                ('mention', models.CharField(blank=True, default='', help_text='例: <!here>、<!channel>、<@U01ABCDEFG>', max_length=100, verbose_name='メンション')),
                ('notify_deadline_reminder', models.BooleanField(default=True, verbose_name='提出期限のリマインド')),
                ('reminder_days_before', models.PositiveSmallIntegerField(default=3, verbose_name='リマインドする日数（期限の何日前）')),
                ('notify_shift_confirmed', models.BooleanField(default=False, verbose_name='メンバーのシフト確定')),
                ('notify_schedule_changed', models.BooleanField(default=True, verbose_name='提出期限・開講スケジュールの変更')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slack_setting', to='custom_auth.group', verbose_name='グループ')),
            ],
            options={
                'verbose_name': 'Slack通知設定',
                'verbose_name_plural': 'Slack通知設定',
            },
        ),
    ]
