# Generated by Django 5.2.17 on 2026-10-01 19:56

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_historicallineaccount_lineaccount'),
        ('shift', '0013_historicalshiftdeadline_reminder_sent_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkType',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='仕事内容')),
                ('hourly_rate', models.PositiveIntegerField(default=0, verbose_name='時給（円）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='表示順')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical 仕事内容',
                'verbose_name_plural': 'historical 仕事内容',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
                ('name', models.CharField(max_length=100, verbose_name='仕事内容')),
                ('hourly_rate', models.PositiveIntegerField(default=0, verbose_name='時給（円）')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.PositiveSmallIntegerField(default=100, verbose_name='表示順')),
            ],
            options={
                'verbose_name': '仕事内容',
                'verbose_name_plural': '仕事内容',
                'ordering': ('display_order', 'name'),
            },
        ),
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ('work_date', 'start_time', 'id'), 'verbose_name': '勤怠実績', 'verbose_name_plural': '勤怠実績'},
        ),
        migrations.RemoveConstraint(
            model_name='attendancerecord',
            name='attendance_record_unique_day',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給（円）'),
        ),
        migrations.AddField(
            model_name='historicalattendancerecord',
            name='hourly_rate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='時給（円）'),
        ),
        migrations.AddField(
            model_name='historicalworktype',
            name='group',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='custom_auth.group', verbose_name='グループ'),
        ),
        migrations.AddField(
            model_name='historicalworktype',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='worktype',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_types', to='custom_auth.group', verbose_name='グループ'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_records', to='shift.worktype', verbose_name='仕事内容'),
        ),
        migrations.AddField(
            model_name='historicalattendancerecord',
            name='work_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shift.worktype', verbose_name='仕事内容'),
        ),
        migrations.AddConstraint(
            model_name='worktype',
            constraint=models.UniqueConstraint(fields=('group', 'name'), name='work_type_unique_name'),
        ),
    ]
