"""
Django settings for shifttimes project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import socket

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY",
                       "django-insecure-*95=ak)4b(lp_#=-0us_g(owo&qk(2n$pcj(dnvkx5t1s%bmgi")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DEBUG", "false").lower() == "true"
ADMIN_MODE = os.environ.get("ADMIN_MODE", "false").lower() == "true"

# オンプレミスモード。自前で1組織向けに運用する構成を想定し、
# 課金(Stripe)まわりを丸ごと無効化してトップページをサイト名だけの表示にする
ONPREMISE_MODE = os.environ.get("ONPREMISE_MODE", "false").lower() == "true"


ALLOWED_HOSTS = os.environ.get("ALLOWED_HOSTS", "*").split(" ")
CSRF_TRUSTED_ORIGINS = os.environ.get("CSRF_TRUSTED_ORIGINS", "http://localhost:8000").split(" ")

# サイト名。オンプレミスモードではトップページの表示名にも使う
SITE_NAME = os.environ.get("SITE_NAME", "シフト管理システム")
SITE_TITLE = SITE_NAME
SITE_HEADER = SITE_NAME

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'shifttimes',
    'custom_auth',
    'notice',
    'shift',
    'simple_history'
]

if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "simple_history.middleware.HistoryRequestMiddleware",
]

ROOT_URLCONF = 'shifttimes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "shifttimes/templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'shifttimes.context_processors.site',
                'shift.context_processors.shift_admin_groups',
                'shift.context_processors.attendance_groups',
            ],
        },
    },
]

WSGI_APPLICATION = 'shifttimes.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

if DEBUG:
    import os
    import socket

    hostname, _, ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS = [ip[:-1] + "1" for ip in ips] + ["127.0.0.1"]
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "ja"
TIME_ZONE = "Asia/Tokyo"
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATICFILES_DIRS = [os.path.join(BASE_DIR, "shifttimes/static")]
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# AUTH_USER_MODEL
AUTH_USER_MODEL = "custom_auth.User"

ADMIN_DOMAIN_URL = os.environ.get("ADMIN_DOMAIN_URL", "test.local")

# Stripe
STRIPE_SECRET_KEY = os.environ.get("STRIPE_SECRET_KEY", "")
STRIPE_PUBLISHABLE_KEY = os.environ.get("STRIPE_PUBLISHABLE_KEY", "")
STRIPE_WEBHOOK_SECRET = os.environ.get("STRIPE_WEBHOOK_SECRET", "")

# 無料プラン（Stripe 契約なしのグループに適用される既定の上限）
FREE_PLAN = {
    "name": "Free",
    "price_id": "",
    "amount": 0,
    "max_members": int(os.environ.get("FREE_PLAN_MAX_MEMBERS", 10)),
    "rank": 0,
    "recommended": False,
}

# 有料プラン。rank は上下比較（アップグレード / ダウングレード判定）に使う
STRIPE_PLANS = {
    "standard": {
        "name": "Standard",
        "price_id": os.environ.get("STRIPE_PRICE_ID_STANDARD", ""),
        "amount": 1980,
        "max_members": 30,
        "rank": 10,
        "recommended": True,
    },
    "pro1": {
        "name": "Pro 1",
        "price_id": os.environ.get("STRIPE_PRICE_ID_PRO1", ""),
        "amount": 4980,
        "max_members": 100,
        "rank": 20,
        "recommended": False,
    },
    "pro2": {
        "name": "Pro 2",
        "price_id": os.environ.get("STRIPE_PRICE_ID_PRO2", ""),
        "amount": 9980,
        "max_members": 250,
        "rank": 30,
        "recommended": False,
    },
}

# 運営が無償付与したグループに適用する上限（max_members=None は無制限）
UNLIMITED_PLAN = {
    "name": "Enterprise",
    "price_id": "",
    "amount": 0,
    "max_members": None,
    "rank": 99,
    "recommended": False,
}

# 問い合わせ先（Enterprise プランの導線）
CONTACT_EMAIL = os.environ.get("CONTACT_EMAIL", "contact@example.com")

# 課金機能が有効か。オンプレミスモードでは請求画面・Webhook・プラン上限をすべて止める
BILLING_ENABLED = not ONPREMISE_MODE

if ONPREMISE_MODE:
    # オンプレミスでの運用は Enterprise プランの契約形態として扱う。
    # 全グループに最初から Enterprise 相当（人数無制限）を適用する
    FREE_PLAN = dict(UNLIMITED_PLAN)
    STRIPE_PLANS = {}
    # キーが残っていると Stripe API を叩ける状態になってしまうため明示的に空にする
    STRIPE_SECRET_KEY = ""
    STRIPE_PUBLISHABLE_KEY = ""
    STRIPE_WEBHOOK_SECRET = ""

# LINE ログイン。チャネル ID とシークレットが両方揃っているときだけ画面に導線が出る。
# 有効・無効の判定は custom_auth.line.is_enabled() に集約している
LINE_LOGIN_CHANNEL_ID = os.environ.get("LINE_LOGIN_CHANNEL_ID", "")
LINE_LOGIN_CHANNEL_SECRET = os.environ.get("LINE_LOGIN_CHANNEL_SECRET", "")

# 認証アプリに表示されるサービス名（TOTP の issuer）
APP_NAME = os.environ.get("APP_NAME", "ShiftTimes")

SITE_URL = os.environ.get("SITE_URL", "http://localhost:8000")
DOMAIN_URL = os.environ.get("DOMAIN_URL", SITE_URL)

# Email
EMAIL_BACKEND = os.environ.get(
    "EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend" if DEBUG
    else "django.core.mail.backends.smtp.EmailBackend",
)
EMAIL_HOST = os.environ.get("EMAIL_HOST", "localhost")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 25))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD", "")
EMAIL_USE_TLS = os.environ.get("EMAIL_USE_TLS", "false").lower() == "true"
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", "no-reply@example.com")

# ユーザーアクティベーション・認証系の有効期限
USER_LOGIN_VERIFY_EMAIL_EXPIRED_HOURS = int(os.environ.get("USER_LOGIN_VERIFY_EMAIL_EXPIRED_HOURS", 72))
USER_LOGIN_VERIFY_EMAIL_EXPIRED_MINUTES = int(os.environ.get("USER_LOGIN_VERIFY_EMAIL_EXPIRED_MINUTES", 30))
SIGN_UP_EXPIRED_DAYS = int(os.environ.get("SIGN_UP_EXPIRED_DAYS", 7))
