# Generated by Django 5.1.7 on 2026-04-03 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='group',
            name='allow_jpnic_add',
        ),
        migrations.RemoveField(
            model_name='group',
            name='allow_service_add',
        ),
        migrations.RemoveField(
            model_name='group',
            name='is_pass',
        ),
        migrations.RemoveField(
            model_name='historicalgroup',
            name='agree',
        ),
        migrations.RemoveField(
            model_name='historicalgroup',
            name='allow_jpnic_add',
        ),
        migrations.RemoveField(
            model_name='historicalgroup',
            name='allow_service_add',
        ),
        migrations.RemoveField(
            model_name='historicalgroup',
            name='is_pass',
        ),
    ]
