# Generated by Django 5.1.7 on 2026-06-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_remove_group_agree_remove_group_allow_jpnic_add_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe(SubID)'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Stripe(SubID)'),
        ),
    ]
