# Generated by Django 5.2.17 on 2026-09-21 01:02

import custom_auth.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0003_group_stripe_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='free_plan',
            field=models.CharField(blank=True, choices=custom_auth.models.free_plan_choices, default='', max_length=50, verbose_name='無償付与プラン'),
        ),
        migrations.AddField(
            model_name='group',
            name='free_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='無償付与の理由'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='期間末に解約予定'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='現在の請求期間の終了日'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_plan',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='契約プラン'),
        ),
        migrations.AddField(
            model_name='group',
            name='stripe_status',
            field=models.CharField(blank=True, choices=[('', '未契約'), ('trialing', 'トライアル中'), ('active', '有効'), ('past_due', '支払い遅延'), ('unpaid', '未払い'), ('incomplete', '決済未完了'), ('incomplete_expired', '決済未完了(期限切れ)'), ('paused', '一時停止'), ('canceled', '解約済み')], default='', max_length=50, verbose_name='契約ステータス'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='free_plan',
            field=models.CharField(blank=True, choices=custom_auth.models.free_plan_choices, default='', max_length=50, verbose_name='無償付与プラン'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='free_reason',
            field=models.CharField(blank=True, default='', max_length=250, verbose_name='無償付与の理由'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='stripe_cancel_at_period_end',
            field=models.BooleanField(default=False, verbose_name='期間末に解約予定'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='stripe_current_period_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='現在の請求期間の終了日'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='stripe_plan',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='契約プラン'),
        ),
        migrations.AddField(
            model_name='historicalgroup',
            name='stripe_status',
            field=models.CharField(blank=True, choices=[('', '未契約'), ('trialing', 'トライアル中'), ('active', '有効'), ('past_due', '支払い遅延'), ('unpaid', '未払い'), ('incomplete', '決済未完了'), ('incomplete_expired', '決済未完了(期限切れ)'), ('paused', '一時停止'), ('canceled', '解約済み')], default='', max_length=50, verbose_name='契約ステータス'),
        ),
        migrations.AlterField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='group_users_set', through='custom_auth.UserGroup', through_fields=('group', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='user_set', through='custom_auth.UserGroup', through_fields=('user', 'group'), to='custom_auth.group'),
        ),
    ]
