# Generated by Django 5.2.17 on 2026-09-21 12:24

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0004_group_free_plan_group_free_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalLineAccount',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('line_user_id', models.CharField(db_index=True, max_length=100, verbose_name='LINEユーザID')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='LINE表示名')),
                ('picture_url', models.URLField(blank=True, default='', max_length=500, verbose_name='アイコンURL')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='LINEでの最終ログイン')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'historical LINE連携',
                'verbose_name_plural': 'historical LINE連携',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='LineAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新日')),
                ('line_user_id', models.CharField(max_length=100, unique=True, verbose_name='LINEユーザID')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='LINE表示名')),
                ('picture_url', models.URLField(blank=True, default='', max_length=500, verbose_name='アイコンURL')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='LINEでの最終ログイン')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザ')),
            ],
            options={
                'verbose_name': 'LINE連携',
                'verbose_name_plural': 'LINE連携',
            },
        ),
    ]
